+ source ../common_lib/fsio_lib.sh
++ source /root/mugen-riscv/libs/locallibs/common_lib.sh
+++ python3 --version
+++ '[' 0 -eq 0 ']'
+++ source /root/mugen-riscv/libs/locallibs/common_lib_python.sh
++ export 'FS_TYPE=ext3 ext4 xfs'
++ FS_TYPE='ext3 ext4 xfs'
++ export LANG=en_US.UTF-8
++ LANG=en_US.UTF-8
++ REMOVE_VG
++ vggroup=
++ [[ '' != '' ]]
+++ df -T
+++ grep test_vggroup
+++ awk '{print $7}'
++ mounted=
++ [[ '' != '' ]]
++ lsblk
++ grep test_vggroup
++ [[ 1 -eq 0 ]]
++ rm -rf '/tmp/point*'
+ main
++ type -t post_test
+ '[' -n function ']'
+ trap post_test EXIT INT HUP TERM
+ rpm -qa
+ grep expect
++ type -t config_params
+ '[' -n '' ']'
++ type -t pre_test
+ '[' -n function ']'
+ pre_test
+ LOG_INFO 'Start to prepare the database config.'
+ message='Start to prepare the database config.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'Start to prepare the database config.'
Fri Sep  1 15:34:22 2023 - INFO  - Start to prepare the database config.
+ point_list=($(CREATE_FS ext3))
++ CREATE_FS ext3
++ fs_type=ext3
+++ date +%Y%m%d%H%M%S
++ cur_date=20230901153422
+++ CREATE_VG
++++ date +%Y%m%d%H%M%S
+++ cur_date=20230901153422
++++ lsblk
++++ grep disk
++++ awk '{print $1}'
++++ tail -n 1
+++ free_disk=vda
+++ disk_name=/dev/vda
+++ pvcreate /dev/vda -f
+++ [[ 5 -eq 0 ]]
++++ pvcreate /dev/vda
++++ grep test_vggroup
++++ cut -d '"' -f 4
+++ vggroup=
+++ printf
printf: usage: printf [-v var] format [arguments]
++ vggroup=
++ count=1
++ msg=' '
++ for fs in ${fs_type[@]}
++ lvname=test_lv120230901153422
++ point=/tmp/point120230901153422
++ lvcreate -n test_lv120230901153422 -L 512M -y
  No command with matching syntax recognised.  Run 'lvcreate --help' for more information.
  Nearest similar command has syntax:
++ mkfs -t ext3 /dev//test_lv120230901153422
mke2fs 1.47.0 (5-Feb-2023)
The file /dev//test_lv120230901153422 does not exist and no size was specified.
++ mkdir /tmp/point120230901153422
++ mount /dev//test_lv120230901153422 /tmp/point120230901153422
mount: /tmp/point120230901153422: special device /dev//test_lv120230901153422 does not exist.
       dmesg(1) may have more information after failed mount system call.
++ msg=' /tmp/point120230901153422 '
++ count=2
++ echo /tmp/point120230901153422
+ vggroup=/tmp/point120230901153422
+ ext3_point=
++ lsblk
++ grep /tmp/point120230901153422
++ awk '{print $1}'
++ cut -d - -f 2
+ lv=
+ LOG_INFO 'Finish to prepare the database config.'
+ message='Finish to prepare the database config.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'Finish to prepare the database config.'
Fri Sep  1 15:34:23 2023 - INFO  - Finish to prepare the database config.
++ type -t run_test
+ '[' -n function ']'
+ run_test
+ LOG_INFO 'Start to run test.'
+ message='Start to run test.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'Start to run test.'
Fri Sep  1 15:34:24 2023 - INFO  - Start to run test.
++ df -i
++ grep /dev/mapper//tmp/point120230901153422-
++ awk '{print $2}'
+ size1=
+ umount /dev//tmp/point120230901153422/
umount: /dev//tmp/point120230901153422/: no mount point specified.
+ e2fsck -fp /dev//tmp/point120230901153422/
e2fsck: No such file or directory while trying to open /dev//tmp/point120230901153422/
Possibly non-existent device?
+ lvresize -L +1G /dev//tmp/point120230901153422/
  "tmp/point120230901153422/": Invalid path for Logical Volume.
+ resize2fs /dev//tmp/point120230901153422/ 6262
resize2fs 1.47.0 (5-Feb-2023)
open: No such file or directory while opening /dev//tmp/point120230901153422/
+ CHECK_RESULT 1 0 0 'Change size of ext3 failed.'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='Change size of ext3 failed.'
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'Change size of ext3 failed.'
+ LOG_ERROR 'Change size of ext3 failed.'
+ message='Change size of ext3 failed.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'Change size of ext3 failed.'
Fri Sep  1 15:34:24 2023 - ERROR - Change size of ext3 failed.
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_FSIO_ext3_resize2fs.sh line 37'
+ message='oe_test_FSIO_ext3_resize2fs.sh line 37'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_FSIO_ext3_resize2fs.sh line 37'
Fri Sep  1 15:34:25 2023 - ERROR - oe_test_FSIO_ext3_resize2fs.sh line 37
+ return 0
+ mount /dev//tmp/point120230901153422/
mount: /dev//tmp/point120230901153422/: can't find in /etc/fstab.
++ df -i
++ grep /dev/mapper//tmp/point120230901153422-
++ awk '{print $2}'
+ size2=
+ [[ '' -ne '' ]]
+ CHECK_RESULT 1 0 0 'Resize for ext3 failed.'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='Resize for ext3 failed.'
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'Resize for ext3 failed.'
+ LOG_ERROR 'Resize for ext3 failed.'
+ message='Resize for ext3 failed.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'Resize for ext3 failed.'
Fri Sep  1 15:34:25 2023 - ERROR - Resize for ext3 failed.
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_FSIO_ext3_resize2fs.sh line 41'
+ message='oe_test_FSIO_ext3_resize2fs.sh line 41'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_FSIO_ext3_resize2fs.sh line 41'
Fri Sep  1 15:34:26 2023 - ERROR - oe_test_FSIO_ext3_resize2fs.sh line 41
+ return 0
+ LOG_INFO 'End to run test.'
+ message='End to run test.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'End to run test.'
Fri Sep  1 15:34:26 2023 - INFO  - End to run test.
+ CASE_RESULT 0
+ case_re=0
+ test -z 2
+ test 2 -gt 0
+ LOG_ERROR 'failed to execute the case.'
+ message='failed to execute the case.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'failed to execute the case.'
Fri Sep  1 15:34:26 2023 - ERROR - failed to execute the case.
+ exit 2
+ post_test
+ LOG_INFO 'Start to restore the test environment.'
+ message='Start to restore the test environment.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'Start to restore the test environment.'
Fri Sep  1 15:34:27 2023 - INFO  - Start to restore the test environment.
++ echo /tmp/point120230901153422
+ list=/tmp/point120230901153422
+ REMOVE_FS /tmp/point120230901153422
+ point_list=($1)
++ seq 0 0
+ for i in $(seq 0 $((${#point_list[@]} - 1)))
+ tmp=/tmp/point120230901153422
++ df -T
++ grep /tmp/point120230901153422
++ awk '{print $1}'
+ lv=
+ [[ '' == '' ]]
+ continue
+ LOG_INFO 'End to restore the test environment.'
+ message='End to restore the test environment.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'End to restore the test environment.'
Fri Sep  1 15:34:27 2023 - INFO  - End to restore the test environment.
