+ source ../common_lib/fsio_lib.sh
++ source /root/mugen-riscv/libs/locallibs/common_lib.sh
+++ python3 --version
+++ '[' 0 -eq 0 ']'
+++ source /root/mugen-riscv/libs/locallibs/common_lib_python.sh
++ export 'FS_TYPE=ext3 ext4 xfs'
++ FS_TYPE='ext3 ext4 xfs'
++ export LANG=en_US.UTF-8
++ LANG=en_US.UTF-8
++ REMOVE_VG
++ vggroup=
++ [[ '' != '' ]]
+++ df -T
+++ grep test_vggroup
+++ awk '{print $7}'
++ mounted=
++ [[ '' != '' ]]
++ lsblk
++ grep test_vggroup
++ [[ 1 -eq 0 ]]
++ rm -rf '/tmp/point*'
+ main
++ type -t post_test
+ '[' -n function ']'
+ trap post_test EXIT INT HUP TERM
+ rpm -qa
+ grep expect
++ type -t config_params
+ '[' -n '' ']'
++ type -t pre_test
+ '[' -n function ']'
+ pre_test
+ LOG_INFO 'Start to prepare the database config.'
+ message='Start to prepare the database config.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'Start to prepare the database config.'
Tue Aug 29 10:14:29 2023 - INFO  - Start to prepare the database config.
++ date +%Y%m%d%H%M%S
+ cur_date=20230829101429
++ CREATE_VG
+++ date +%Y%m%d%H%M%S
++ cur_date=20230829101429
+++ lsblk
+++ grep disk
+++ awk '{print $1}'
+++ tail -n 1
++ free_disk=vda
++ disk_name=/dev/vda
++ pvcreate /dev/vda -f
++ [[ 127 -eq 0 ]]
+++ grep test_vggroup
+++ cut -d '"' -f 4
+++ pvcreate /dev/vda
++ vggroup=
++ printf
printf: usage: printf [-v var] format [arguments]
+ vggroup=
+ lv=test_lv20230829101429
+ lvcreate -n test_lv20230829101429 -L 2G -y
oe_test_FSIO_mount_umount_ext3.sh: line 26: lvcreate: command not found
+ mkfs.ext3 /dev//test_lv20230829101429
mke2fs 1.47.0 (5-Feb-2023)
The file /dev//test_lv20230829101429 does not exist and no size was specified.
+ ext3_mount=/mnt/ext3_mount20230829101429
+ mkdir /mnt/ext3_mount20230829101429
+ LOG_INFO 'Finish to prepare the database config.'
+ message='Finish to prepare the database config.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'Finish to prepare the database config.'
Tue Aug 29 10:14:29 2023 - INFO  - Finish to prepare the database config.
++ type -t run_test
+ '[' -n function ']'
+ run_test
+ LOG_INFO 'Start to run test.'
+ message='Start to run test.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'Start to run test.'
Tue Aug 29 10:14:29 2023 - INFO  - Start to run test.
+ mount -t ext3 /dev//test_lv20230829101429 /mnt/ext3_mount20230829101429
mount: /mnt/ext3_mount20230829101429: special device /dev//test_lv20230829101429 does not exist.
       dmesg(1) may have more information after failed mount system call.
+ CHECK_RESULT 32 0 0 'mount ext3 failed.'
+ actual_result=32
+ expect_result=0
+ mode=0
+ error_log='mount ext3 failed.'
+ '[' -z 32 ']'
+ '[' 0 -eq 0 ']'
+ test 32x '!=' 0x
+ test -n 'mount ext3 failed.'
+ LOG_ERROR 'mount ext3 failed.'
+ message='mount ext3 failed.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'mount ext3 failed.'
Tue Aug 29 10:14:29 2023 - ERROR - mount ext3 failed.
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_FSIO_mount_umount_ext3.sh line 36'
+ message='oe_test_FSIO_mount_umount_ext3.sh line 36'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_FSIO_mount_umount_ext3.sh line 36'
Tue Aug 29 10:14:29 2023 - ERROR - oe_test_FSIO_mount_umount_ext3.sh line 36
+ return 0
+ df -h
+ grep /mnt/ext3_mount20230829101429
+ CHECK_RESULT 1 0 0 'Check mount infos failed.'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='Check mount infos failed.'
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'Check mount infos failed.'
+ LOG_ERROR 'Check mount infos failed.'
+ message='Check mount infos failed.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'Check mount infos failed.'
Tue Aug 29 10:14:29 2023 - ERROR - Check mount infos failed.
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_FSIO_mount_umount_ext3.sh line 38'
+ message='oe_test_FSIO_mount_umount_ext3.sh line 38'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_FSIO_mount_umount_ext3.sh line 38'
Tue Aug 29 10:14:29 2023 - ERROR - oe_test_FSIO_mount_umount_ext3.sh line 38
+ return 0
+ umount /mnt/ext3_mount20230829101429
umount: /mnt/ext3_mount20230829101429: not mounted.
+ CHECK_RESULT 32 0 0 'umount ext3 failed.'
+ actual_result=32
+ expect_result=0
+ mode=0
+ error_log='umount ext3 failed.'
+ '[' -z 32 ']'
+ '[' 0 -eq 0 ']'
+ test 32x '!=' 0x
+ test -n 'umount ext3 failed.'
+ LOG_ERROR 'umount ext3 failed.'
+ message='umount ext3 failed.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'umount ext3 failed.'
Tue Aug 29 10:14:29 2023 - ERROR - umount ext3 failed.
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_FSIO_mount_umount_ext3.sh line 40'
+ message='oe_test_FSIO_mount_umount_ext3.sh line 40'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_FSIO_mount_umount_ext3.sh line 40'
Tue Aug 29 10:14:29 2023 - ERROR - oe_test_FSIO_mount_umount_ext3.sh line 40
+ return 0
++ blkid
++ grep /dev/mapper/-test_lv20230829101429
++ awk '{print $2}'
++ cut -d '"' -f 2
+ uuid=
+ mount UUID= /mnt/ext3_mount20230829101429
mount: /mnt/ext3_mount20230829101429: special device UUID= does not exist.
       dmesg(1) may have more information after failed mount system call.
+ df -h
+ grep /mnt/ext3_mount20230829101429
+ CHECK_RESULT 1 0 0 'Check mount infos failed.'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='Check mount infos failed.'
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'Check mount infos failed.'
+ LOG_ERROR 'Check mount infos failed.'
+ message='Check mount infos failed.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'Check mount infos failed.'
Tue Aug 29 10:14:29 2023 - ERROR - Check mount infos failed.
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_FSIO_mount_umount_ext3.sh line 44'
+ message='oe_test_FSIO_mount_umount_ext3.sh line 44'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_FSIO_mount_umount_ext3.sh line 44'
Tue Aug 29 10:14:29 2023 - ERROR - oe_test_FSIO_mount_umount_ext3.sh line 44
+ return 0
+ umount /mnt/ext3_mount20230829101429
umount: /mnt/ext3_mount20230829101429: not mounted.
+ CHECK_RESULT 32 0 0 'umount ext3 failed.'
+ actual_result=32
+ expect_result=0
+ mode=0
+ error_log='umount ext3 failed.'
+ '[' -z 32 ']'
+ '[' 0 -eq 0 ']'
+ test 32x '!=' 0x
+ test -n 'umount ext3 failed.'
+ LOG_ERROR 'umount ext3 failed.'
+ message='umount ext3 failed.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'umount ext3 failed.'
Tue Aug 29 10:14:29 2023 - ERROR - umount ext3 failed.
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_FSIO_mount_umount_ext3.sh line 46'
+ message='oe_test_FSIO_mount_umount_ext3.sh line 46'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_FSIO_mount_umount_ext3.sh line 46'
Tue Aug 29 10:14:29 2023 - ERROR - oe_test_FSIO_mount_umount_ext3.sh line 46
+ return 0
+ LOG_INFO 'End to run test.'
+ message='End to run test.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'End to run test.'
Tue Aug 29 10:14:29 2023 - INFO  - End to run test.
+ CASE_RESULT 0
+ case_re=0
+ test -z 5
+ test 5 -gt 0
+ LOG_ERROR 'failed to execute the case.'
+ message='failed to execute the case.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'failed to execute the case.'
Tue Aug 29 10:14:29 2023 - ERROR - failed to execute the case.
+ exit 5
+ post_test
+ LOG_INFO 'Start to restore the test environment.'
+ message='Start to restore the test environment.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'Start to restore the test environment.'
Tue Aug 29 10:14:29 2023 - INFO  - Start to restore the test environment.
+ rm -rf /mnt/ext3_mount20230829101429
+ LOG_INFO 'End to restore the test environment.'
+ message='End to restore the test environment.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'End to restore the test environment.'
Tue Aug 29 10:14:29 2023 - INFO  - End to restore the test environment.
