+ source ./common/disk_lib.sh
++ source /root/mugen-riscv/libs/locallibs/common_lib.sh
+++ python3 --version
+++ '[' 0 -eq 0 ']'
+++ source /root/mugen-riscv/libs/locallibs/common_lib_python.sh
+ main
++ type -t post_test
+ '[' -n function ']'
+ trap post_test EXIT INT HUP TERM
+ rpm -qa
+ grep expect
++ type -t config_params
+ '[' -n '' ']'
++ type -t pre_test
+ '[' -n function ']'
+ pre_test
+ LOG_INFO 'Start to prepare the test environment!'
+ message='Start to prepare the test environment!'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'Start to prepare the test environment!'
Thu Aug 31 17:25:12 2023 - INFO  - Start to prepare the test environment!
+ DNF_INSTALL lvm2
+ pkgs=lvm2
+ node=1
+ '[' -z '' ']'
+ tmpfile=
++ python3 /root/mugen-riscv/libs/locallibs/rpm_manage.py install --pkgs lvm2 --node 1 --tempfile ''
Thu Aug 31 17:25:20 2023 - INFO  - pkgs:(lvm2) is already installed
+ tmpfile2=
+ '[' -z '' ']'
+ tmpfile=
+ check_free_disk
++ TEST_DISK
++ id=1
++ python3 /root/mugen-riscv/libs/locallibs/get_test_device.py --device disk --node 1
+ disks=
+ disk_list=($disks)
+ local_disk=
+ local_disk1=
+ local_disk2=
+ local_disk3=
++ cat /etc/os-release
++ grep VERSION_ID
++ awk -F = '{print$NF}'
++ awk -F '"' '{print$2}'
+ version_id=23.09
+ LOG_INFO 'End to prepare the test environment!'
+ message='End to prepare the test environment!'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'End to prepare the test environment!'
Thu Aug 31 17:25:28 2023 - INFO  - End to prepare the test environment!
++ type -t run_test
+ '[' -n function ']'
+ run_test
+ LOG_INFO 'Start executing testcase!'
+ message='Start executing testcase!'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'Start executing testcase!'
Thu Aug 31 17:25:29 2023 - INFO  - Start executing testcase!
+ pvcreate -y /dev/
  No device found for /dev/.
+ CHECK_RESULT 5 0 0 'create PV failed'
+ actual_result=5
+ expect_result=0
+ mode=0
+ error_log='create PV failed'
+ '[' -z 5 ']'
+ '[' 0 -eq 0 ']'
+ test 5x '!=' 0x
+ test -n 'create PV failed'
+ LOG_ERROR 'create PV failed'
+ message='create PV failed'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'create PV failed'
Thu Aug 31 17:25:30 2023 - ERROR - create PV failed
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_lvm2_vgchange_001.sh line 31'
+ message='oe_test_lvm2_vgchange_001.sh line 31'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_lvm2_vgchange_001.sh line 31'
Thu Aug 31 17:25:30 2023 - ERROR - oe_test_lvm2_vgchange_001.sh line 31
+ return 0
+ pvs
+ grep /dev/
+ CHECK_RESULT 1 0 0 'create PV failed'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='create PV failed'
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'create PV failed'
+ LOG_ERROR 'create PV failed'
+ message='create PV failed'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'create PV failed'
Thu Aug 31 17:25:31 2023 - ERROR - create PV failed
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_lvm2_vgchange_001.sh line 33'
+ message='oe_test_lvm2_vgchange_001.sh line 33'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_lvm2_vgchange_001.sh line 33'
Thu Aug 31 17:25:31 2023 - ERROR - oe_test_lvm2_vgchange_001.sh line 33
+ return 0
+ vgcreate test /dev/
  No device found for /dev/.
+ CHECK_RESULT 5 0 0 'create VG failed'
+ actual_result=5
+ expect_result=0
+ mode=0
+ error_log='create VG failed'
+ '[' -z 5 ']'
+ '[' 0 -eq 0 ']'
+ test 5x '!=' 0x
+ test -n 'create VG failed'
+ LOG_ERROR 'create VG failed'
+ message='create VG failed'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'create VG failed'
Thu Aug 31 17:25:32 2023 - ERROR - create VG failed
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_lvm2_vgchange_001.sh line 35'
+ message='oe_test_lvm2_vgchange_001.sh line 35'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_lvm2_vgchange_001.sh line 35'
Thu Aug 31 17:25:33 2023 - ERROR - oe_test_lvm2_vgchange_001.sh line 35
+ return 0
+ vgdisplay
+ grep 'VG Name'
+ grep test
+ CHECK_RESULT 1 0 0 'create VG failed'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='create VG failed'
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'create VG failed'
+ LOG_ERROR 'create VG failed'
+ message='create VG failed'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'create VG failed'
Thu Aug 31 17:25:33 2023 - ERROR - create VG failed
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_lvm2_vgchange_001.sh line 37'
+ message='oe_test_lvm2_vgchange_001.sh line 37'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_lvm2_vgchange_001.sh line 37'
Thu Aug 31 17:25:34 2023 - ERROR - oe_test_lvm2_vgchange_001.sh line 37
+ return 0
+ vgchange --logicalvolume 1 test
+ grep 'Volume group "test" successfully changed'
  Volume group "test" not found
  Cannot process volume group test
+ CHECK_RESULT 1 0 0 'vgchange logicalvolume size failed'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='vgchange logicalvolume size failed'
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'vgchange logicalvolume size failed'
+ LOG_ERROR 'vgchange logicalvolume size failed'
+ message='vgchange logicalvolume size failed'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'vgchange logicalvolume size failed'
Thu Aug 31 17:25:34 2023 - ERROR - vgchange logicalvolume size failed
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_lvm2_vgchange_001.sh line 39'
+ message='oe_test_lvm2_vgchange_001.sh line 39'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_lvm2_vgchange_001.sh line 39'
Thu Aug 31 17:25:35 2023 - ERROR - oe_test_lvm2_vgchange_001.sh line 39
+ return 0
+ lvcreate -L 0.1MB -n lv test
+ grep created
  Volume group "test" not found
  Cannot process volume group test
+ CHECK_RESULT 1 0 0 'create LV failed'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='create LV failed'
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'create LV failed'
+ LOG_ERROR 'create LV failed'
+ message='create LV failed'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'create LV failed'
Thu Aug 31 17:25:36 2023 - ERROR - create LV failed
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_lvm2_vgchange_001.sh line 41'
+ message='oe_test_lvm2_vgchange_001.sh line 41'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_lvm2_vgchange_001.sh line 41'
Thu Aug 31 17:25:36 2023 - ERROR - oe_test_lvm2_vgchange_001.sh line 41
+ return 0
+ lvcreate -L 0.1MB -n lv1 test
+ grep 'Maximum number of logical volumes (1) reached'
+ CHECK_RESULT 1 0 0 'Maximum number of logical volumes (1) reached'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='Maximum number of logical volumes (1) reached'
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'Maximum number of logical volumes (1) reached'
+ LOG_ERROR 'Maximum number of logical volumes (1) reached'
+ message='Maximum number of logical volumes (1) reached'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'Maximum number of logical volumes (1) reached'
Thu Aug 31 17:25:37 2023 - ERROR - Maximum number of logical volumes (1) reached
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_lvm2_vgchange_001.sh line 43'
+ message='oe_test_lvm2_vgchange_001.sh line 43'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_lvm2_vgchange_001.sh line 43'
Thu Aug 31 17:25:38 2023 - ERROR - oe_test_lvm2_vgchange_001.sh line 43
+ return 0
+ vgchange --maxphysicalvolumes 1 test
+ grep 'Volume group "test" successfully changed'
+ CHECK_RESULT 1 0 0 'set maxphysicalvolumes failed'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='set maxphysicalvolumes failed'
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'set maxphysicalvolumes failed'
+ LOG_ERROR 'set maxphysicalvolumes failed'
+ message='set maxphysicalvolumes failed'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'set maxphysicalvolumes failed'
Thu Aug 31 17:25:38 2023 - ERROR - set maxphysicalvolumes failed
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_lvm2_vgchange_001.sh line 45'
+ message='oe_test_lvm2_vgchange_001.sh line 45'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_lvm2_vgchange_001.sh line 45'
Thu Aug 31 17:25:39 2023 - ERROR - oe_test_lvm2_vgchange_001.sh line 45
+ return 0
+ pvcreate -y /dev/
  No device found for /dev/.
+ CHECK_RESULT 5 0 0 'create PV failed'
+ actual_result=5
+ expect_result=0
+ mode=0
+ error_log='create PV failed'
+ '[' -z 5 ']'
+ '[' 0 -eq 0 ']'
+ test 5x '!=' 0x
+ test -n 'create PV failed'
+ LOG_ERROR 'create PV failed'
+ message='create PV failed'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'create PV failed'
Thu Aug 31 17:25:39 2023 - ERROR - create PV failed
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_lvm2_vgchange_001.sh line 47'
+ message='oe_test_lvm2_vgchange_001.sh line 47'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_lvm2_vgchange_001.sh line 47'
Thu Aug 31 17:25:40 2023 - ERROR - oe_test_lvm2_vgchange_001.sh line 47
+ return 0
+ vgextend test /dev/
+ grep 'PV /dev/ cannot be added to VG test'
+ CHECK_RESULT 1 0 0 'vgextend failed'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='vgextend failed'
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'vgextend failed'
+ LOG_ERROR 'vgextend failed'
+ message='vgextend failed'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'vgextend failed'
Thu Aug 31 17:25:41 2023 - ERROR - vgextend failed
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_lvm2_vgchange_001.sh line 49'
+ message='oe_test_lvm2_vgchange_001.sh line 49'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_lvm2_vgchange_001.sh line 49'
Thu Aug 31 17:25:41 2023 - ERROR - oe_test_lvm2_vgchange_001.sh line 49
+ return 0
+ lvremove -f lv test
+ grep 'successfully removed'
  Volume group "lv" not found
  Cannot process volume group lv
  Volume group "test" not found
  Cannot process volume group test
+ CHECK_RESULT 1 0 0 'lvremove failed'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='lvremove failed'
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'lvremove failed'
+ LOG_ERROR 'lvremove failed'
+ message='lvremove failed'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'lvremove failed'
Thu Aug 31 17:25:42 2023 - ERROR - lvremove failed
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_lvm2_vgchange_001.sh line 51'
+ message='oe_test_lvm2_vgchange_001.sh line 51'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_lvm2_vgchange_001.sh line 51'
Thu Aug 31 17:25:42 2023 - ERROR - oe_test_lvm2_vgchange_001.sh line 51
+ return 0
+ vgchange -u test
+ grep 'Volume group "test" successfully changed'
  Volume group "test" not found
  Cannot process volume group test
+ CHECK_RESULT 1 0 0 'vgchange -u failed'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='vgchange -u failed'
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'vgchange -u failed'
+ LOG_ERROR 'vgchange -u failed'
+ message='vgchange -u failed'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'vgchange -u failed'
Thu Aug 31 17:25:43 2023 - ERROR - vgchange -u failed
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_lvm2_vgchange_001.sh line 53'
+ message='oe_test_lvm2_vgchange_001.sh line 53'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_lvm2_vgchange_001.sh line 53'
Thu Aug 31 17:25:44 2023 - ERROR - oe_test_lvm2_vgchange_001.sh line 53
+ return 0
+ vgchange --resizeable n test
+ grep 'Volume group "test" successfully changed'
  Volume group "test" not found
  Cannot process volume group test
+ CHECK_RESULT 1 0 0 'vgchange --resizeable no failed'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='vgchange --resizeable no failed'
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'vgchange --resizeable no failed'
+ LOG_ERROR 'vgchange --resizeable no failed'
+ message='vgchange --resizeable no failed'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'vgchange --resizeable no failed'
Thu Aug 31 17:25:44 2023 - ERROR - vgchange --resizeable no failed
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_lvm2_vgchange_001.sh line 55'
+ message='oe_test_lvm2_vgchange_001.sh line 55'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_lvm2_vgchange_001.sh line 55'
Thu Aug 31 17:25:45 2023 - ERROR - oe_test_lvm2_vgchange_001.sh line 55
+ return 0
+ vgchange --resizeable y test
+ grep 'Volume group "test" successfully changed'
  Volume group "test" not found
  Cannot process volume group test
+ CHECK_RESULT 1 0 0 'vgchange --resizeable yes failed'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='vgchange --resizeable yes failed'
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'vgchange --resizeable yes failed'
+ LOG_ERROR 'vgchange --resizeable yes failed'
+ message='vgchange --resizeable yes failed'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'vgchange --resizeable yes failed'
Thu Aug 31 17:25:46 2023 - ERROR - vgchange --resizeable yes failed
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_lvm2_vgchange_001.sh line 57'
+ message='oe_test_lvm2_vgchange_001.sh line 57'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_lvm2_vgchange_001.sh line 57'
Thu Aug 31 17:25:46 2023 - ERROR - oe_test_lvm2_vgchange_001.sh line 57
+ return 0
+ vgchange --addtag tag test
+ grep 'Volume group "test" successfully changed'
  Volume group "test" not found
  Cannot process volume group test
+ CHECK_RESULT 1 0 0 'vgchange add tag failed'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='vgchange add tag failed'
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'vgchange add tag failed'
+ LOG_ERROR 'vgchange add tag failed'
+ message='vgchange add tag failed'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'vgchange add tag failed'
Thu Aug 31 17:25:47 2023 - ERROR - vgchange add tag failed
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_lvm2_vgchange_001.sh line 59'
+ message='oe_test_lvm2_vgchange_001.sh line 59'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_lvm2_vgchange_001.sh line 59'
Thu Aug 31 17:25:48 2023 - ERROR - oe_test_lvm2_vgchange_001.sh line 59
+ return 0
+ vgchange --deltag tag test
+ grep 'Volume group "test" successfully changed'
  Volume group "test" not found
  Cannot process volume group test
+ CHECK_RESULT 1 0 0 'vgchange del tag failed'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='vgchange del tag failed'
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'vgchange del tag failed'
+ LOG_ERROR 'vgchange del tag failed'
+ message='vgchange del tag failed'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'vgchange del tag failed'
Thu Aug 31 17:25:48 2023 - ERROR - vgchange del tag failed
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_lvm2_vgchange_001.sh line 61'
+ message='oe_test_lvm2_vgchange_001.sh line 61'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_lvm2_vgchange_001.sh line 61'
Thu Aug 31 17:25:49 2023 - ERROR - oe_test_lvm2_vgchange_001.sh line 61
+ return 0
+ vgchange --vgmetadatacopies all test
+ grep 'Volume group "test" successfully changed'
  Volume group "test" not found
  Cannot process volume group test
+ CHECK_RESULT 1 0 0 'vgchange --vgmetadatacopies all failed'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='vgchange --vgmetadatacopies all failed'
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'vgchange --vgmetadatacopies all failed'
+ LOG_ERROR 'vgchange --vgmetadatacopies all failed'
+ message='vgchange --vgmetadatacopies all failed'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'vgchange --vgmetadatacopies all failed'
Thu Aug 31 17:25:50 2023 - ERROR - vgchange --vgmetadatacopies all failed
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_lvm2_vgchange_001.sh line 63'
+ message='oe_test_lvm2_vgchange_001.sh line 63'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_lvm2_vgchange_001.sh line 63'
Thu Aug 31 17:25:50 2023 - ERROR - oe_test_lvm2_vgchange_001.sh line 63
+ return 0
+ '[23.09' = '22.03]'
oe_test_lvm2_vgchange_001.sh: line 64: [23.09: command not found
+ LOG_INFO 'End executing testcase!'
+ message='End executing testcase!'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'End executing testcase!'
Thu Aug 31 17:25:51 2023 - INFO  - End executing testcase!
+ CASE_RESULT 0
+ case_re=0
+ test -z 17
+ test 17 -gt 0
+ LOG_ERROR 'failed to execute the case.'
+ message='failed to execute the case.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'failed to execute the case.'
Thu Aug 31 17:25:51 2023 - ERROR - failed to execute the case.
+ exit 17
+ post_test
+ LOG_INFO 'Start environment cleanup.'
+ message='Start environment cleanup.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'Start environment cleanup.'
Thu Aug 31 17:25:52 2023 - INFO  - Start environment cleanup.
+ vgremove -f test
  Volume group "test" not found
  Cannot process volume group test
+ pvremove -f /dev/ /dev/
  No device found for /dev/.
  No device found for /dev/.
+ DNF_REMOVE
+ node=1
+ pkg_list=
+ mode=0
+ [[ -z '' ]]
+ [[ -z '' ]]
+ LOG_WARN 'no thing to do.'
+ message='no thing to do.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level warn --message 'no thing to do.'
Thu Aug 31 17:25:53 2023 - WARN  - no thing to do.
+ return 0
+ LOG_INFO 'Finish environment cleanup.'
+ message='Finish environment cleanup.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'Finish environment cleanup.'
Thu Aug 31 17:25:53 2023 - INFO  - Finish environment cleanup.
