+ source ../common_lib/fsio_lib.sh
++ source /root/mugen-riscv/libs/locallibs/common_lib.sh
+++ python3 --version
+++ '[' 0 -eq 0 ']'
+++ source /root/mugen-riscv/libs/locallibs/common_lib_python.sh
++ export 'FS_TYPE=ext3 ext4 xfs'
++ FS_TYPE='ext3 ext4 xfs'
++ export LANG=en_US.UTF-8
++ LANG=en_US.UTF-8
++ REMOVE_VG
++ vggroup=
++ [[ '' != '' ]]
+++ df -T
+++ grep test_vggroup
+++ awk '{print $7}'
++ mounted=
++ [[ '' != '' ]]
++ lsblk
++ grep test_vggroup
++ [[ 1 -eq 0 ]]
++ rm -rf '/tmp/point*'
+ main
++ type -t post_test
+ '[' -n function ']'
+ trap post_test EXIT INT HUP TERM
+ rpm -qa
+ grep expect
++ type -t config_params
+ '[' -n '' ']'
++ type -t pre_test
+ '[' -n function ']'
+ pre_test
+ LOG_INFO 'Start to prepare the database config.'
+ message='Start to prepare the database config.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'Start to prepare the database config.'
Tue Aug 29 10:15:03 2023 - INFO  - Start to prepare the database config.
++ date +%Y%m%d%H%M%S
+ cur_date=20230829101503
++ CREATE_VG
+++ date +%Y%m%d%H%M%S
++ cur_date=20230829101503
+++ lsblk
+++ grep disk
+++ awk '{print $1}'
+++ tail -n 1
++ free_disk=vda
++ disk_name=/dev/vda
++ pvcreate /dev/vda -f
++ [[ 127 -eq 0 ]]
+++ pvcreate /dev/vda
+++ grep test_vggroup
+++ cut -d '"' -f 4
++ vggroup=
++ printf
printf: usage: printf [-v var] format [arguments]
+ vggroup=
+ lv=test_lv20230829101503
+ lvcreate -n test_lv20230829101503 -L 2G -y
oe_test_FSIO_mount_ext3_rw.sh: line 26: lvcreate: command not found
+ mkfs.ext3 /dev//test_lv20230829101503
mke2fs 1.47.0 (5-Feb-2023)
The file /dev//test_lv20230829101503 does not exist and no size was specified.
+ ext3_point=test20230829101503
+ mkdir test20230829101503
+ LOG_INFO 'Finish to prepare the database config.'
+ message='Finish to prepare the database config.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'Finish to prepare the database config.'
Tue Aug 29 10:15:03 2023 - INFO  - Finish to prepare the database config.
++ type -t run_test
+ '[' -n function ']'
+ run_test
+ LOG_INFO 'Start to run test.'
+ message='Start to run test.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'Start to run test.'
Tue Aug 29 10:15:03 2023 - INFO  - Start to run test.
+ mount -t ext3 -o rw /dev//test_lv20230829101503 test20230829101503
mount: /root/mugen-riscv/testcases/system-test/fs-test/FS_FileSystem/test20230829101503: special device /dev//test_lv20230829101503 does not exist.
       dmesg(1) may have more information after failed mount system call.
+ CHECK_RESULT 32 0 0 'Mount ext3 by ro failed.'
+ actual_result=32
+ expect_result=0
+ mode=0
+ error_log='Mount ext3 by ro failed.'
+ '[' -z 32 ']'
+ '[' 0 -eq 0 ']'
+ test 32x '!=' 0x
+ test -n 'Mount ext3 by ro failed.'
+ LOG_ERROR 'Mount ext3 by ro failed.'
+ message='Mount ext3 by ro failed.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'Mount ext3 by ro failed.'
Tue Aug 29 10:15:03 2023 - ERROR - Mount ext3 by ro failed.
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_FSIO_mount_ext3_rw.sh line 36'
+ message='oe_test_FSIO_mount_ext3_rw.sh line 36'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_FSIO_mount_ext3_rw.sh line 36'
Tue Aug 29 10:15:03 2023 - ERROR - oe_test_FSIO_mount_ext3_rw.sh line 36
+ return 0
+ echo 'test create file'
+ grep test test20230829101503/testFile
test create file
+ CHECK_RESULT 0 0 0 'Create file on ext3 failed.'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='Create file on ext3 failed.'
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ LOG_INFO 'End to run test.'
+ message='End to run test.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'End to run test.'
Tue Aug 29 10:15:03 2023 - INFO  - End to run test.
+ CASE_RESULT 0
+ case_re=0
+ test -z 1
+ test 1 -gt 0
+ LOG_ERROR 'failed to execute the case.'
+ message='failed to execute the case.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'failed to execute the case.'
Tue Aug 29 10:15:03 2023 - ERROR - failed to execute the case.
+ exit 1
+ post_test
+ LOG_INFO 'Start to restore the test environment.'
+ message='Start to restore the test environment.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'Start to restore the test environment.'
Tue Aug 29 10:15:03 2023 - INFO  - Start to restore the test environment.
+ REMOVE_FS test20230829101503
+ point_list=($1)
++ seq 0 0
+ for i in $(seq 0 $((${#point_list[@]} - 1)))
+ tmp=test20230829101503
++ df -T
++ grep test20230829101503
++ awk '{print $1}'
+ lv=
+ [[ '' == '' ]]
+ continue
+ LOG_INFO 'End to restore the test environment.'
+ message='End to restore the test environment.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'End to restore the test environment.'
Tue Aug 29 10:15:03 2023 - INFO  - End to restore the test environment.
