+ source ../common_lib/fsio_lib.sh
++ source /root/mugen-riscv/libs/locallibs/common_lib.sh
+++ python3 --version
+++ '[' 0 -eq 0 ']'
+++ source /root/mugen-riscv/libs/locallibs/common_lib_python.sh
++ export 'FS_TYPE=ext3 ext4 xfs'
++ FS_TYPE='ext3 ext4 xfs'
++ export LANG=en_US.UTF-8
++ LANG=en_US.UTF-8
++ REMOVE_VG
++ vggroup=
++ [[ '' != '' ]]
+++ df -T
+++ grep test_vggroup
+++ awk '{print $7}'
++ mounted=
++ [[ '' != '' ]]
++ lsblk
++ grep test_vggroup
++ [[ 1 -eq 0 ]]
++ rm -rf /tmp/point120230829144906 /tmp/point220230829144906 /tmp/point320230829144906
+ main
++ type -t post_test
+ '[' -n function ']'
+ trap post_test EXIT INT HUP TERM
+ rpm -qa
+ grep expect
++ type -t config_params
+ '[' -n '' ']'
++ type -t pre_test
+ '[' -n function ']'
+ pre_test
+ LOG_INFO 'Start environment preparation.'
+ message='Start environment preparation.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'Start environment preparation.'
Tue Aug 29 14:49:11 2023 - INFO  - Start environment preparation.
+ point_list=($(CREATE_FS))
++ CREATE_FS
++ fs_type='ext3 ext4 xfs'
+++ date +%Y%m%d%H%M%S
++ cur_date=20230829144911
+++ CREATE_VG
++++ date +%Y%m%d%H%M%S
+++ cur_date=20230829144911
++++ lsblk
++++ grep disk
++++ awk '{print $1}'
++++ tail -n 1
+++ free_disk=vda
+++ disk_name=/dev/vda
+++ pvcreate /dev/vda -f
+++ [[ 127 -eq 0 ]]
++++ grep test_vggroup
++++ pvcreate /dev/vda
++++ cut -d '"' -f 4
+++ vggroup=
+++ printf
printf: usage: printf [-v var] format [arguments]
++ vggroup=
++ count=1
++ msg=' '
++ for fs in ${fs_type[@]}
++ lvname=test_lv120230829144911
++ point=/tmp/point120230829144911
++ lvcreate -n test_lv120230829144911 -L 512M -y
../common_lib/fsio_lib.sh: line 107: lvcreate: command not found
++ mkfs -t ext3 /dev//test_lv120230829144911
mke2fs 1.47.0 (5-Feb-2023)
The file /dev//test_lv120230829144911 does not exist and no size was specified.
++ mkdir /tmp/point120230829144911
++ mount /dev//test_lv120230829144911 /tmp/point120230829144911
mount: /tmp/point120230829144911: special device /dev//test_lv120230829144911 does not exist.
       dmesg(1) may have more information after failed mount system call.
++ msg=' /tmp/point120230829144911 '
++ count=2
++ for fs in ${fs_type[@]}
++ lvname=test_lv220230829144911
++ point=/tmp/point220230829144911
++ lvcreate -n test_lv220230829144911 -L 512M -y
../common_lib/fsio_lib.sh: line 107: lvcreate: command not found
++ mkfs -t ext4 /dev//test_lv220230829144911
mke2fs 1.47.0 (5-Feb-2023)
The file /dev//test_lv220230829144911 does not exist and no size was specified.
++ mkdir /tmp/point220230829144911
++ mount /dev//test_lv220230829144911 /tmp/point220230829144911
mount: /tmp/point220230829144911: special device /dev//test_lv220230829144911 does not exist.
       dmesg(1) may have more information after failed mount system call.
++ msg=' /tmp/point120230829144911 /tmp/point220230829144911 '
++ count=3
++ for fs in ${fs_type[@]}
++ lvname=test_lv320230829144911
++ point=/tmp/point320230829144911
++ lvcreate -n test_lv320230829144911 -L 512M -y
../common_lib/fsio_lib.sh: line 107: lvcreate: command not found
++ mkfs -t xfs /dev//test_lv320230829144911
mkfs: failed to execute mkfs.xfs: No such file or directory
++ mkdir /tmp/point320230829144911
++ mount /dev//test_lv320230829144911 /tmp/point320230829144911
mount: /tmp/point320230829144911: special device /dev//test_lv320230829144911 does not exist.
       dmesg(1) may have more information after failed mount system call.
++ msg=' /tmp/point120230829144911 /tmp/point220230829144911 /tmp/point320230829144911 '
++ count=4
++ echo /tmp/point120230829144911 /tmp/point220230829144911 /tmp/point320230829144911
+ LOG_INFO 'End of environmental preparation!'
+ message='End of environmental preparation!'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'End of environmental preparation!'
Tue Aug 29 14:49:11 2023 - INFO  - End of environmental preparation!
++ type -t run_test
+ '[' -n function ']'
+ run_test
+ LOG_INFO 'Start to run test.'
+ message='Start to run test.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'Start to run test.'
Tue Aug 29 14:49:11 2023 - INFO  - Start to run test.
++ seq 1 2
+ for i in $(seq 1 $((${#point_list[@]} - 1)))
+ var=/tmp/point220230829144911
+ echo /tmp/point220230829144911
+ filefrag -v /tmp/point220230829144911/testFile
/tmp/point220230829144911/testFile: FIBMAP/FIEMAP unsupported
Filesystem type is: 1021994
File size of /tmp/point220230829144911/testFile is 26 (1 block of 4096 bytes)
+ CHECK_RESULT 22 0 0 'Check filefrag of /tmp/point220230829144911/testFile failed.'
+ actual_result=22
+ expect_result=0
+ mode=0
+ error_log='Check filefrag of /tmp/point220230829144911/testFile failed.'
+ '[' -z 22 ']'
+ '[' 0 -eq 0 ']'
+ test 22x '!=' 0x
+ test -n 'Check filefrag of /tmp/point220230829144911/testFile failed.'
+ LOG_ERROR 'Check filefrag of /tmp/point220230829144911/testFile failed.'
+ message='Check filefrag of /tmp/point220230829144911/testFile failed.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'Check filefrag of /tmp/point220230829144911/testFile failed.'
Tue Aug 29 14:49:11 2023 - ERROR - Check filefrag of /tmp/point220230829144911/testFile failed.
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_FSIO_filefrag.sh line 33'
+ message='oe_test_FSIO_filefrag.sh line 33'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_FSIO_filefrag.sh line 33'
Tue Aug 29 14:49:11 2023 - ERROR - oe_test_FSIO_filefrag.sh line 33
+ return 0
+ for i in $(seq 1 $((${#point_list[@]} - 1)))
+ var=/tmp/point320230829144911
+ echo /tmp/point320230829144911
+ filefrag -v /tmp/point320230829144911/testFile
/tmp/point320230829144911/testFile: FIBMAP/FIEMAP unsupported
Filesystem type is: 1021994
File size of /tmp/point320230829144911/testFile is 26 (1 block of 4096 bytes)
+ CHECK_RESULT 22 0 0 'Check filefrag of /tmp/point320230829144911/testFile failed.'
+ actual_result=22
+ expect_result=0
+ mode=0
+ error_log='Check filefrag of /tmp/point320230829144911/testFile failed.'
+ '[' -z 22 ']'
+ '[' 0 -eq 0 ']'
+ test 22x '!=' 0x
+ test -n 'Check filefrag of /tmp/point320230829144911/testFile failed.'
+ LOG_ERROR 'Check filefrag of /tmp/point320230829144911/testFile failed.'
+ message='Check filefrag of /tmp/point320230829144911/testFile failed.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'Check filefrag of /tmp/point320230829144911/testFile failed.'
Tue Aug 29 14:49:11 2023 - ERROR - Check filefrag of /tmp/point320230829144911/testFile failed.
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_FSIO_filefrag.sh line 33'
+ message='oe_test_FSIO_filefrag.sh line 33'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_FSIO_filefrag.sh line 33'
Tue Aug 29 14:49:11 2023 - ERROR - oe_test_FSIO_filefrag.sh line 33
+ return 0
+ LOG_INFO 'End to run test.'
+ message='End to run test.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'End to run test.'
Tue Aug 29 14:49:11 2023 - INFO  - End to run test.
+ CASE_RESULT 0
+ case_re=0
+ test -z 2
+ test 2 -gt 0
+ LOG_ERROR 'failed to execute the case.'
+ message='failed to execute the case.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'failed to execute the case.'
Tue Aug 29 14:49:11 2023 - ERROR - failed to execute the case.
+ exit 2
+ post_test
+ LOG_INFO 'Start to restore the test environment.'
+ message='Start to restore the test environment.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'Start to restore the test environment.'
Tue Aug 29 14:49:11 2023 - INFO  - Start to restore the test environment.
++ echo /tmp/point120230829144911 /tmp/point220230829144911 /tmp/point320230829144911
+ list='/tmp/point120230829144911 /tmp/point220230829144911 /tmp/point320230829144911'
+ REMOVE_FS '/tmp/point120230829144911 /tmp/point220230829144911 /tmp/point320230829144911'
+ point_list=($1)
++ seq 0 2
+ for i in $(seq 0 $((${#point_list[@]} - 1)))
+ tmp=/tmp/point120230829144911
++ grep /tmp/point120230829144911
++ df -T
++ awk '{print $1}'
+ lv=
+ [[ '' == '' ]]
+ continue
+ for i in $(seq 0 $((${#point_list[@]} - 1)))
+ tmp=/tmp/point220230829144911
++ df -T
++ grep /tmp/point220230829144911
++ awk '{print $1}'
+ lv=
+ [[ '' == '' ]]
+ continue
+ for i in $(seq 0 $((${#point_list[@]} - 1)))
+ tmp=/tmp/point320230829144911
++ df -T
++ grep /tmp/point320230829144911
++ awk '{print $1}'
+ lv=
+ [[ '' == '' ]]
+ continue
+ LOG_INFO 'End to restore the test environment.'
+ message='End to restore the test environment.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'End to restore the test environment.'
Tue Aug 29 14:49:11 2023 - INFO  - End to restore the test environment.
